---

- name: Create location hostgroup in FreeIPA server
  ipa_hostgroup:
    cn:          '{{ freeipa_client__ipa_hostgroup_name_pattern }}'
    description: 'Servers physically located to {{ freeipa_client__ipa_ns_host_location }}'
    ipa_host:    '{{ freeipa_client__ipa_enroll_host }}'
    ipa_pass:    '{{ freeipa_client__ipa_enroll_pass }}'
    ipa_user:    '{{ freeipa_client__ipa_enroll_user }}'
    state:       present
  when: freeipa_client__ipa_hostgroup_name_pattern is defined
  register: _freeipa_client__location_hostgroup

- import_tasks: configure-manually.yml
  when: ansible_os_family in ['Debian']

- import_tasks: configure-client.yml
  when: ansible_os_family in ['RedHat']

- name: Add this host to location hostgroup members in FreeIPA server
  ipa_hostgroup:
    cn:       '{{ freeipa_client__ipa_hostgroup_name_pattern }}'
    host:     '{{ _freeipa_client__location_hostgroup.hostgroup.member_host|d([]) + [freeipa_client__ipa_fqdn] }}'
    ipa_host: '{{ freeipa_client__ipa_enroll_host }}'
    ipa_pass: '{{ freeipa_client__ipa_enroll_pass }}'
    ipa_user: '{{ freeipa_client__ipa_enroll_user }}'
    state:    present
  when: freeipa_client__ipa_hostgroup_name_pattern is defined and
          _freeipa_client__location_hostgroup|success

- import_tasks: configure-pam.yml
