---

# Perform installation with the ipa-client-install command

- name: Check if host is enrolled
  stat:
    path: /etc/ipa/default.conf
  register: _freeipa_client_ipaconf
  check_mode: no
  tags: ['freeipa-client', 'freeipa-client-configure']

- name: Enroll host in FreeIPA master
  command: >
    {{ freeipa_client__install_command }}
    {{'--hostname=' + freeipa_client__hostname if freeipa_client__hostname is defined else ''}}
    --server={{ freeipa_client__server }}
    --domain={{ freeipa_client__domain }}
    --principal={{ freeipa_client__enroll_user }}
    --password={{ freeipa_client__enroll_pass }}
    --ssh-trust-dns
    {% if freeipa_client__enable_make_homedir %}--mkhomedir{% endif %}
    {% if freeipa_client__enable_dns_updates %}--enable-dns-updates{% endif %}
    --unattended
    {{ '--all-ip-addresses' if freeipa_client__all_ip_addresses else ''}}
    {{ '--no-ntp' if not freeipa_client__enable_ntp else ''}}
    {{ '--force-join' if freeipa_client__force_join else ''}}
  when: not _freeipa_client_ipaconf.stat.exists
  tags: ['freeipa-client', 'freeipa-client-configure']
