---

- name: Register host to FreeIPA server
  ipa_host:
    fqdn:                 '{{ freeipa_client__ipa_fqdn }}'
    ip_address:           '{{ freeipa_client__ipa_dns_ip|d(omit) }}'
    ipa_host:             '{{ freeipa_client__ipa_enroll_host }}'
    ipa_pass:             '{{ freeipa_client__ipa_enroll_pass }}'
    ipa_user:             '{{ freeipa_client__ipa_enroll_user }}'
    state:                present
  register: _freeipa_client__manual_host_register
  failed_when: "_freeipa_client__manual_host_register.msg is defined and
        _freeipa_client__manual_host_register.msg != 'response host_mod: no modifications to be performed'"
  delegate_to: "{{ freeipa_client__ipa_delegate_to if freeipa_client__ipa_delegate_to is defined else omit }}"


## IPA client configuration


- name: Ensure configuration directory exists
  file:
    path:  "{{ freeipa_client__config_dir }}"
    owner: root
    group: root
    mode:  0755
    state: directory

- name: Download ipa certificate to host
  get_url:
    url:  'http://{{ freeipa_client__ipa_enroll_host }}/ipa/config/ca.crt'
    dest: '{{ freeipa_client__ca_path }}'
    mode: 0644
    checksum: '{{ freeipa_client__ca_checksum|d(omit) }}'
