---

- name: Assert required variables
  assert:
    that:
      - freeipa_client__domain is defined
      - freeipa_client__server is defined
      - freeipa_client__ipa_enroll_host is defined
      - freeipa_client__ipa_enroll_user is defined
      - freeipa_client__ipa_enroll_pass is defined
