---
# tasks file for freeipa-client

- name: Include the OS specific variables
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
        - defaults.yml
      skip: true
  tags: ['always']

- name: Importing initialization tasks
  import_tasks: init.yml
  tags: ['always']

- name: Importing install tasks
  import_tasks: install.yml
  tags: ['freeipa-client', 'freeipa-client-install']

- name: Importing configuration tasks
  import_tasks: configure.yml
  tags: ['freeipa-client', 'freeipa-client-configure']

- name: Optionally including facts tasks
  include_tasks: facts.yml
  when: freeipa_client__facts|bool
  tags: ['freeipa-client', 'freeipa-client-facts']
