---
# tasks file for freeipa-client

- name: Include the OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - "defaults.yml"
      skip: true
  tags: ['always']

- debug: var=item
  with_items:
    - '{{ freeipa_client__ipa_sshfp_dns_zone_name }}'
    - '{{ inventory_hostname }}'
    - "{{ inventory_hostname.split('.')[1:]|join('.') }}"
    - '{{ freeipa_client__ipa_sshfp_dns_entry_name }}'
    - '{{ ansible_hostname }}'
  tags: ['always']

- import_tasks: init.yml
  tags: ['always']

- import_tasks: install.yml
  tags: ['freeipa-client', 'freeipa-client-install']

- import_tasks: configure.yml
  tags: ['freeipa-client', 'freeipa-client-configure']

- import_tasks: service.yml
  tags: ['freeipa-client', 'freeipa-client-service']
