---
- name: Setup /etc/krb5.conf
  template:
    src:    'etc/krb5.conf.j2'
    dest:   '/etc/krb5.conf'
    owner:  'root'
    group:  'root'
    mode:   '0644'
    backup: yes
  notify: [ 'restart sssd' ]
  tags: ['freeipa-client', 'manual-install']

- name: Setup /etc/sssd/sssd.conf
  template:
    src:    'etc/sssd/sssd.conf.j2'
    dest:   '/etc/sssd/sssd.conf'
    owner:  'root'
    group:  'root'
    mode:   '0600'
    backup: yes
  notify: [ 'restart sssd']
  tags: ['freeipa-client', 'manual-install']

- name: Ensure SSSD is started and enabled on boot
  service:
    name: sssd
    state: started
    enabled: yes
  changed_when: False
  tags: ['freeipa-client', 'manual-install']
